{
    "id": 484379,
    "tags": [],
    "site": 87,
    "on_show_events": [],
    "portals": [
        2296760,
        2296759,
        2296758,
        2296757
    ],
    "area": 2182,
    "meta": {
        "portals": [
            {
                "id": 2296760,
                "site": 87,
                "created": "2022-08-18T12:30:18.944156+04:00",
                "modified": "2022-08-18T12:30:18.944191+04:00",
                "deleted": null,
                "uuid": "0d855c20-6529-420a-b5f0-9657f67f35a4",
                "source_ref": null,
                "portal": 12,
                "active": false,
                "expiration_date": null,
                "reference": null,
                "last_log": null,
                "last_message": "Listing is not set to feed to this portal",
                "feed_status": "disabled",
                "on_portal": false,
                "development_id": null,
                "publish_street_address": false,
                "publish_map_to_address": false,
                "publish_feature_notes": false,
                "display_price": null,
                "zoning": null,
                "residential": 484379,
                "holiday": null,
                "commercial": null,
                "project": null,
                "statistics": null,
                "meta": {
                    "portal": {
                        "id": 12,
                        "name": "Property Finder",
                        "slug": "property-finder"
                    }
                }
            },
            {
                "id": 2296759,
                "site": 87,
                "created": "2022-08-18T12:30:18.769509+04:00",
                "modified": "2022-08-18T12:30:18.769534+04:00",
                "deleted": null,
                "uuid": "af237735-328a-4f57-af4a-3170b06eaba4",
                "source_ref": null,
                "portal": 13,
                "active": false,
                "expiration_date": null,
                "reference": null,
                "last_log": null,
                "last_message": "Listing is not set to feed to this portal",
                "feed_status": "disabled",
                "on_portal": false,
                "development_id": null,
                "publish_street_address": false,
                "publish_map_to_address": false,
                "publish_feature_notes": false,
                "display_price": null,
                "zoning": null,
                "residential": 484379,
                "holiday": null,
                "commercial": null,
                "project": null,
                "statistics": null,
                "meta": {
                    "portal": {
                        "id": 13,
                        "name": "Bayut",
                        "slug": "bayut"
                    }
                }
            },
            {
                "id": 2296758,
                "site": 87,
                "created": "2022-08-18T12:30:18.532989+04:00",
                "modified": "2022-08-18T12:30:18.533012+04:00",
                "deleted": null,
                "uuid": "6905f8d9-5239-4d01-a871-90088c04bd8b",
                "source_ref": null,
                "portal": 14,
                "active": false,
                "expiration_date": null,
                "reference": null,
                "last_log": null,
                "last_message": "Listing is not set to feed to this portal",
                "feed_status": "disabled",
                "on_portal": false,
                "development_id": null,
                "publish_street_address": false,
                "publish_map_to_address": false,
                "publish_feature_notes": false,
                "display_price": null,
                "zoning": null,
                "residential": 484379,
                "holiday": null,
                "commercial": null,
                "project": null,
                "statistics": null,
                "meta": {
                    "portal": {
                        "id": 14,
                        "name": "Dubizzle",
                        "slug": "dubizzle"
                    }
                }
            },
            {
                "id": 2296757,
                "site": 87,
                "created": "2022-08-18T12:30:18.338376+04:00",
                "modified": "2022-09-12T17:04:48.001074+04:00",
                "deleted": null,
                "uuid": "1ea851fd-b1c1-4e76-8903-3187e2c76354",
                "source_ref": null,
                "portal": 24,
                "active": true,
                "expiration_date": null,
                "reference": null,
                "last_log": null,
                "last_message": "Pending syndication",
                "feed_status": "pending",
                "on_portal": false,
                "development_id": null,
                "publish_street_address": false,
                "publish_map_to_address": false,
                "publish_feature_notes": false,
                "display_price": null,
                "zoning": null,
                "residential": 484379,
                "holiday": null,
                "commercial": null,
                "project": null,
                "statistics": null,
                "meta": {
                    "portal": {
                        "id": 24,
                        "name": "Houza",
                        "slug": "houza"
                    }
                }
            }
        ],
        "tags": []
    },
    "description": "<p>Engel & Voelkers is proud to present to you this stunning two-bedroom residence in Dubai Creekside, located in Dubai Health Care City II. The upcoming Ritz-Carlton Residences and Mansions present the best in wellness hospitality with personalized attention, refined and memorable experiences and innovative lifestyle enhancements offering an unrivaled level of quality of life.</p><p><strong>Property Details:</strong></p><p>- Completion in Q1 2025<br />- Unit type: Apartment<br />- View: Panoramic Creek View + Burj Khalifa + Garden Resort<br />- Unit Size from: 2,885.00 sq. ft.<br />- Bedroom/s: 2<br />- Bathroom/s: 3<br />- Furnished Fully Fitted Kitchen Built-in Wardrobes<br />- 4 Step Payment Plan: 5% down payment on the date of purchase 4% OQOOD registration on the date of purchase Registration fees on the date of purchase 15% 02nd installment 20% 03rd installment 60% upon completion </p><strong>About Al Jaddaf:</strong><br /><p>Located in western Dubai in Bur Dubai, Al Jaddaf is bordered to the north and east by the Dubai Creek, to the south and west by Zabeel and Umm Hurair. This area is still developing to a huge hotel hub with up to 5 Hotels at present in construction and 3 hotels build namely Mariott Al Jadaf and Arabian Park Hotel. </p><p>Engel & Voelkers is one of the worlds leading service companies specializing in the brokerage of residential and commercial properties, yachts and aviation, with 900 offices in over 30 countries.<br /><br />Contact Engel & Voelkers today or visit www.engelvoelkers.com/dubai for further details.</p> <br /> PROPERTY FEATURES:  <br />-Balcony <br />-Basement parking <br />-Broadband ready <br />-Built in wardrobes <br />-Central air conditioning <br />-Central heating <br />-Fully fitted kitchen <br />-Fully furnished <br />-Maid's room <br />-Satellite/Cable TV <br />-Shared swimming pool <br />-View of gardens <br />-View of sea/water <br />-24 hours Maintenance <br />-Recreational Facilities <br />-Restaurants",
    "translated_descriptions": null,
    "valuation": null,
    "web_ref": "EVO-S-22208",
    "model": "residential",
    "property_type": "Apartment",
    "extras": "Balcony\nBasement parking\nBroadband ready\nBuilt in wardrobes\nCentral air conditioning\nCentral heating\nFully fitted kitchen\nFully furnished\nMaid's room\nSatellite/Cable TV\nShared swimming pool\nView of gardens\nView of sea/water\n24 hours Maintenance\nRecreational Facilities\nRestaurants",
    "marketing_heading": "The Ritz-Carlton Residences|Investment|High ROI",
    "created": "2022-08-18T12:30:17.606824+04:00",
    "modified": "2022-10-12T18:10:49.161805+04:00",
    "deleted": null,
    "uuid": "35ee1af9-b558-4759-b1a7-5507ec5a99a1",
    "source_ref": "bcrm-import-EVO-S-22208",
    "branch": 1672,
    "agent": 18281,
    "agent_2": null,
    "agent_3": null,
    "agent_4": null,
    "poa": false,
    "owner_viewing_arrangements": null,
    "location": 30629,
    "is_custom_location": false,
    "unit_number": "C2-402",
    "street_number": "934",
    "street_name": "Street",
    "mapping_option": null,
    "complex_name": "Keturah Resort",
    "publish_street_address": false,
    "map_image": 8913165,
    "map_x_position": "55.31883",
    "map_y_position": "25.20746",
    "team": null,
    "display_on_website": true,
    "display_on_branch": false,
    "display_on_team": false,
    "display_on_agent": false,
    "display_on_agent_2": false,
    "display_on_agent_3": false,
    "display_on_agent_4": false,
    "feature_on_newsletter": false,
    "feature_on_agent_newsletter": false,
    "featured": false,
    "header_images": null,
    "listing_images": [
        8915203,
        8915209,
        8915210,
        8915212,
        8915215,
        8915216,
        8915218,
        8915219,
        8915222,
        8915224,
        8915225,
        8915226,
        8915227,
        8915228,
        8915229,
        8915231
    ],
    "floor_plans": null,
    "documents": null,
    "private_documents": null,
    "on_show": false,
    "on_show_directions": null,
    "on_show_date": null,
    "on_show_every_saturday": false,
    "on_show_every_sunday": false,
    "on_show_start_time": null,
    "on_show_end_time": null,
    "search_vector": "'-402':7 '22208':5 '484379':1 '6510915900':14 '934':12 'c2':6 'evo':3 'evo-s':2 'keturah':8,10 'null':15,16,17,18 'resort':9,11 's':4 'street':13",
    "video_streaming_platform": "YouTube",
    "video_id": null,
    "owners": [
        2065069
    ],
    "tenant": null,
    "tenant_lease_ends": null,
    "tenant_notice_period": null,
    "tenant_rental": null,
    "tenant_notes": null,
    "owner_notes": null,
    "deposit": null,
    "lightstone_id": null,
    "lightstone_data": null,
    "building_name": "Keturah Resort",
    "erf_number": null,
    "feed_to_portals": true,
    "matterport_id": null,
    "virtual_tour": null,
    "eyespy360": null,
    "external_link_name": null,
    "external_link_url": null,
    "property_title": null,
    "developer": null,
    "build_year": null,
    "build_completion_status": "Off Plan",
    "property_permit": "6510915900",
    "permit_expiry_date": null,
    "status": "Active",
    "price": "12694000.00",
    "price_reduced": false,
    "price_reduced_alert": false,
    "sold_status_date": null,
    "sold_price": null,
    "sold_agent": null,
    "valuation_price": null,
    "viewing_contact_person": null,
    "viewing_contact_number": null,
    "viewing_notes": null,
    "disable_repayment_calulator": false,
    "disable_transfer_calulator": false,
    "disable_cost_calulator": false,
    "mandate_commission_amount": null,
    "mandate_commission_split": null,
    "land_size": "0.00",
    "floor_size": "2885.00",
    "land_size_measurement_type": "Square Metres",
    "floor_size_measurement_type": "Square Feet",
    "mandate_commission_split_notes": null,
    "price_term": "Per Month",
    "lease_period": null,
    "lease_excludes": null,
    "enable_offers": false,
    "offer_status": null,
    "offers_from": null,
    "offers_increment": null,
    "supporting_status": null,
    "bank_repossessed": false,
    "distressed": false,
    "public_tender": false,
    "no_transfer_cost": false,
    "bank_name": null,
    "quick_sell_options": null,
    "quick_sell_ref": null,
    "escalation": null,
    "annual_escalation": null,
    "available_from": null,
    "occupation_date": null,
    "mandate_type": null,
    "mandate_start_date": null,
    "mandate_end_date": null,
    "mandate_reason_for_selling": null,
    "mandate_notes": null,
    "mandate_commission_percentage": null,
    "on_market_since": null,
    "listing_type": "For Sale",
    "security": false,
    "auction": false,
    "auction_lots": null,
    "auction_venue": null,
    "auction_lat": null,
    "auction_lng": null,
    "auction_date": null,
    "auction_start_time": null,
    "auction_end_time": null,
    "auction_notes": null,
    "subject_to_confirmation": true,
    "guide_price": null,
    "commission_percentage": null,
    "reserve_price": null,
    "starting_price": null,
    "minimum_bid_increment": null,
    "bid_time_extension": null,
    "monthly_rates": null,
    "monthly_levy": null,
    "sectional_title_levy": null,
    "special_levy": null,
    "num_shares": null,
    "share_block_number": null,
    "sectional_scheme_name": null,
    "section_number": null,
    "section_plan_number": null,
    "per_quota": null,
    "body_corp_name": null,
    "body_corp_chairman": null,
    "body_corp_telephone_number": null,
    "supervisor_name": null,
    "supervisor_telephone_number": null,
    "managing_agent": null,
    "managing_agent_telephone_number": null,
    "floor_number": null,
    "payment_frequency": null,
    "bathrooms": "3.0",
    "bathrooms_notes": null,
    "property_notes": null,
    "property_sold_rented_to": null,
    "sold_rented_by_3rd_party": false,
    "seller_feedback_config": null,
    "municipal_value": null,
    "brochures": null,
    "bedrooms": "2.0",
    "bedrooms_notes": null,
    "study": "0.0",
    "study_notes": null,
    "lounges": "0.0",
    "lounges_notes": null,
    "dining_rooms": "0.0",
    "dining_rooms_notes": null,
    "kitchen": "0.0",
    "kitchen_notes": null,
    "laundry": null,
    "laundry_notes": null,
    "patio": null,
    "patio_notes": null,
    "balcony": null,
    "balcony_notes": null,
    "garages": "0.0",
    "garages_notes": null,
    "carports": "2.0",
    "carports_notes": null,
    "flatlet": "0.0",
    "flatlet_notes": null,
    "domestic_accommodation": "0.0",
    "domestic_accommodation_notes": null,
    "flooring": null,
    "flooring_notes": null,
    "exterior": null,
    "exterior_notes": null,
    "roof": null,
    "roof_notes": null,
    "pool": false,
    "pool_notes": null,
    "garden_type": null,
    "garden_type_notes": null,
    "sea_views": false,
    "sea_views_notes": null,
    "security_notes": null,
    "store_room": false,
    "store_room_notes": null,
    "walling": null,
    "walling_notes": null,
    "pets_allowed": false,
    "pets_notes": null,
    "private_seller": false,
    "retirement_unit": false,
    "student_accommodation": false,
    "furnished": false,
    "open_hour_date": null,
    "open_hour_time": null,
    "open_hour_agent": null,
    "open_hour_agent_telephone_number": null,
    "bond_bank": null,
    "bond_bank_branch": null,
    "bond_bank_account_number": null,
    "bond_bank_balance": null,
    "managing_agent_email": null,
    "body_corp_email": null,
    "supervisor_email": null,
    "statistics": 560274,
    "quality": 536489,
    "project": null
},
{
    "id": 484392,
    "tags": [],
    "site": 87,
    "on_show_events": [],
    "portals": [
        2296816,
        2296815,
        2296814,
        2296813
    ],
    "area": 2203,
    "meta": {
        "portals": [
            {
                "id": 2296816,
                "site": 87,
                "created": "2022-08-18T12:36:14.556007+04:00",
                "modified": "2022-10-19T14:44:37.452717+04:00",
                "deleted": null,
                "uuid": "2a8cd40d-3dd0-4f3c-8e69-c0daa5f328cd",
                "source_ref": null,
                "portal": 12,
                "active": true,
                "expiration_date": null,
                "reference": null,
                "last_log": null,
                "last_message": "Pending syndication",
                "feed_status": "pending",
                "on_portal": false,
                "development_id": null,
                "publish_street_address": false,
                "publish_map_to_address": false,
                "publish_feature_notes": false,
                "display_price": null,
                "zoning": null,
                "residential": 484392,
                "holiday": null,
                "commercial": null,
                "project": null,
                "statistics": null,
                "meta": {
                    "portal": {
                        "id": 12,
                        "name": "Property Finder",
                        "slug": "property-finder"
                    }
                }
            },
            {
                "id": 2296815,
                "site": 87,
                "created": "2022-08-18T12:36:14.355630+04:00",
                "modified": "2022-10-19T14:44:37.720843+04:00",
                "deleted": null,
                "uuid": "1be3fc88-f238-45c9-86a3-e608b337c15a",
                "source_ref": null,
                "portal": 13,
                "active": true,
                "expiration_date": null,
                "reference": null,
                "last_log": null,
                "last_message": "Pending syndication",
                "feed_status": "pending",
                "on_portal": false,
                "development_id": null,
                "publish_street_address": false,
                "publish_map_to_address": false,
                "publish_feature_notes": false,
                "display_price": null,
                "zoning": null,
                "residential": 484392,
                "holiday": null,
                "commercial": null,
                "project": null,
                "statistics": null,
                "meta": {
                    "portal": {
                        "id": 13,
                        "name": "Bayut",
                        "slug": "bayut"
                    }
                }
            },
            {
                "id": 2296814,
                "site": 87,
                "created": "2022-08-18T12:36:14.149001+04:00",
                "modified": "2022-10-19T13:21:40.707912+04:00",
                "deleted": null,
                "uuid": "38f87940-0f53-4508-890d-323eca5c1fee",
                "source_ref": null,
                "portal": 14,
                "active": false,
                "expiration_date": null,
                "reference": null,
                "last_log": null,
                "last_message": "Listing is not set to feed to this portal",
                "feed_status": "disabled",
                "on_portal": false,
                "development_id": null,
                "publish_street_address": false,
                "publish_map_to_address": false,
                "publish_feature_notes": false,
                "display_price": null,
                "zoning": null,
                "residential": 484392,
                "holiday": null,
                "commercial": null,
                "project": null,
                "statistics": null,
                "meta": {
                    "portal": {
                        "id": 14,
                        "name": "Dubizzle",
                        "slug": "dubizzle"
                    }
                }
            },
            {
                "id": 2296813,
                "site": 87,
                "created": "2022-08-18T12:36:13.951527+04:00",
                "modified": "2022-10-19T14:44:38.073017+04:00",
                "deleted": null,
                "uuid": "8d7145e5-5a27-4d41-b558-e83c8f6616f3",
                "source_ref": null,
                "portal": 24,
                "active": true,
                "expiration_date": null,
                "reference": null,
                "last_log": null,
                "last_message": "Pending syndication",
                "feed_status": "pending",
                "on_portal": false,
                "development_id": null,
                "publish_street_address": false,
                "publish_map_to_address": false,
                "publish_feature_notes": false,
                "display_price": null,
                "zoning": null,
                "residential": 484392,
                "holiday": null,
                "commercial": null,
                "project": null,
                "statistics": null,
                "meta": {
                    "portal": {
                        "id": 24,
                        "name": "Houza",
                        "slug": "houza"
                    }
                }
            }
        ],
        "tags": []
    },
    "description": "Engel & Voelkers is proud to offer this amazing 2-bedroom apartment on a high floor in Burj Khalifa, Downtown.\n\nProperty Details:\n\n- Biggest Layout 2 bedroom Apartment\n- 2056 sq.ft.\n- DIFC and Sea views\n- Fully Fitted Kitchen\n- Maid Room\n- Study Room\n- Big Living Room\n\nAmenities & Facilities:\n\n- Indoor link to Dubai Mall\n- Sky lounge for residents (123rd floor)\n- 24/7 Concierge\n- Tennis Court x 2 + Basketball on Saturdays\n- Gym + Swimming Pool x 2\n- Business Center on 43rd Floor\n- Meeting Rooms on the 43rd and 76th Floor\n- Zoom Supermarket on Ground Floor\n- 6 Armani Restaurants with a 15% discount for residents\n- Housekeeping, carwash, and laundry available as a service\n\n\nAbout Downtown Dubai:\n\nDowntown Dubai is described as the ‘Centre of Now’. Considered the most iconic neighborhood thanks to the towering Burj Khalifa, dancing fountains and the gigantic Dubai Mall. It's a unique mix of residential towers and commercial precincts making it most sought exciting and extremely modern community in Dubai.\n\nEngel & Voelkers is one of the world’s leading service companies specializing in the brokerage of residential and commercial properties, yachts and aviation, with 800 offices in over 30 countries.\n\nContact Engel & Voelkers today for further details.",
    "translated_descriptions": null,
    "valuation": null,
    "web_ref": "EVO-S-22673",
    "model": "residential",
    "property_type": "Apartment",
    "extras": "Basement parking\nBroadband ready\nBroadband ready\nBuilt in wardrobes\nCarpets\nCentral air conditioning\nCentral heating\nFully fitted kitchen\nFully furnished\nGazebo and outdoor entertaining area\nGymnasium\nIntercom\nJacuzzi\nLandscaped Garden\nLaundry/washing room\nMaid's room\nOn high floor\nSatellite/Cable TV\nShared swimming pool\nSolid wood floors\nStudy\nView of gardens\nView of sea/water\n24 hours Maintenance\nBank/ATM Facility\nBus services\nBusiness Center\nChildren's nursery\nChildren's play area\nCommunal gardens\nConcierge service\nCycling tracks\nFitness Center\nLaundry Service\nMetro station\nMosque\nPolo club and clubhouse\nPublic park\nPublic parking\nPublic transport\nRecreational Facilities\nRestaurants\nShopping mall\nShops\nValet Service\nWalking Trails",
    "marketing_heading": "Best Price|Big Layout|High Floor|Study plus Maid",
    "created": "2022-11-25T13:43:24.617018+04:00",
    "modified": "2022-11-25T14:36:03.342733+04:00",
    "deleted": null,
    "uuid": "f5aa5c85-0733-4b0e-99b2-b97791940e98",
    "source_ref": "bcrm-import-EVO-S-22673",
    "branch": 1673,
    "agent": 18293,
    "agent_2": null,
    "agent_3": null,
    "agent_4": null,
    "poa": false,
    "owner_viewing_arrangements": null,
    "location": 25306,
    "is_custom_location": false,
    "unit_number": "6507",
    "street_number": "851",
    "street_name": "Street",
    "mapping_option": "Address",
    "complex_name": "Burj Khalifa",
    "publish_street_address": false,
    "map_image": 8913525,
    "map_x_position": "55.27423",
    "map_y_position": "25.19735",
    "team": null,
    "display_on_website": true,
    "display_on_branch": false,
    "display_on_team": false,
    "display_on_agent": false,
    "display_on_agent_2": false,
    "display_on_agent_3": false,
    "display_on_agent_4": false,
    "feature_on_newsletter": false,
    "feature_on_agent_newsletter": false,
    "featured": false,
    "header_images": null,
    "listing_images": [
        9808429,
        9808430,
        9808431,
        9808432,
        9808433,
        9808434,
        9808435,
        9808436,
        9808437,
        9808438,
        9808439,
        9808440,
        9808441,
        9808442
    ],
    "floor_plans": null,
    "documents": null,
    "private_documents": [
        12741023,
        12741021,
        12741022,
        12741018
    ],
    "on_show": false,
    "on_show_directions": null,
    "on_show_date": null,
    "on_show_every_saturday": false,
    "on_show_every_sunday": false,
    "on_show_start_time": null,
    "on_show_end_time": null,
    "search_vector": "'22673':5 '484392':1 '6507':6 '7122038900':13 '851':11 'burj':7,9 'evo':3 'evo-s':2 'khalifa':8,10 'null':14,15,16,17 's':4 'street':12",
    "video_streaming_platform": "YouTube",
    "video_id": null,
    "owners": [
        2065373
    ],
    "tenant": null,
    "tenant_lease_ends": null,
    "tenant_notice_period": null,
    "tenant_rental": null,
    "tenant_notes": null,
    "owner_notes": null,
    "deposit": null,
    "lightstone_id": null,
    "lightstone_data": null,
    "building_name": "Burj Khalifa",
    "erf_number": null,
    "feed_to_portals": true,
    "matterport_id": null,
    "virtual_tour": null,
    "eyespy360": null,
    "external_link_name": null,
    "external_link_url": null,
    "property_title": null,
    "developer": null,
    "build_year": null,
    "build_completion_status": "Completed",
    "property_permit": "7122038900",
    "permit_expiry_date": null,
    "status": "Active",
    "price": "4500000.00",
    "price_reduced": false,
    "price_reduced_alert": false,
    "sold_status_date": null,
    "sold_price": null,
    "sold_agent": null,
    "valuation_price": null,
    "viewing_contact_person": null,
    "viewing_contact_number": null,
    "viewing_notes": null,
    "disable_repayment_calulator": false,
    "disable_transfer_calulator": false,
    "disable_cost_calulator": false,
    "mandate_commission_amount": null,
    "mandate_commission_split": null,
    "land_size": "0.00",
    "floor_size": "2056.00",
    "land_size_measurement_type": "Square Metres",
    "floor_size_measurement_type": "Square Feet",
    "mandate_commission_split_notes": null,
    "price_term": "Per Month",
    "lease_period": null,
    "lease_excludes": null,
    "enable_offers": false,
    "offer_status": null,
    "offers_from": null,
    "offers_increment": null,
    "supporting_status": null,
    "bank_repossessed": false,
    "distressed": false,
    "public_tender": false,
    "no_transfer_cost": false,
    "bank_name": null,
    "quick_sell_options": null,
    "quick_sell_ref": null,
    "escalation": null,
    "annual_escalation": null,
    "available_from": null,
    "occupation_date": null,
    "mandate_type": null,
    "mandate_start_date": null,
    "mandate_end_date": null,
    "mandate_reason_for_selling": null,
    "mandate_notes": null,
    "mandate_commission_percentage": null,
    "on_market_since": null,
    "listing_type": "For Sale",
    "security": false,
    "auction": false,
    "auction_lots": null,
    "auction_venue": null,
    "auction_lat": null,
    "auction_lng": null,
    "auction_date": null,
    "auction_start_time": null,
    "auction_end_time": null,
    "auction_notes": null,
    "subject_to_confirmation": true,
    "guide_price": null,
    "commission_percentage": null,
    "reserve_price": null,
    "starting_price": null,
    "minimum_bid_increment": null,
    "bid_time_extension": null,
    "monthly_rates": null,
    "monthly_levy": null,
    "sectional_title_levy": null,
    "special_levy": null,
    "num_shares": null,
    "share_block_number": null,
    "sectional_scheme_name": null,
    "section_number": null,
    "section_plan_number": null,
    "per_quota": null,
    "body_corp_name": null,
    "body_corp_chairman": null,
    "body_corp_telephone_number": null,
    "supervisor_name": null,
    "supervisor_telephone_number": null,
    "managing_agent": null,
    "managing_agent_telephone_number": null,
    "floor_number": null,
    "payment_frequency": null,
    "bathrooms": "4.0",
    "bathrooms_notes": null,
    "property_notes": null,
    "property_sold_rented_to": null,
    "sold_rented_by_3rd_party": false,
    "seller_feedback_config": null,
    "municipal_value": null,
    "brochures": null,
    "bedrooms": "2.0",
    "bedrooms_notes": null,
    "study": "0.0",
    "study_notes": null,
    "lounges": "0.0",
    "lounges_notes": null,
    "dining_rooms": "0.0",
    "dining_rooms_notes": null,
    "kitchen": "0.0",
    "kitchen_notes": null,
    "laundry": null,
    "laundry_notes": null,
    "patio": null,
    "patio_notes": null,
    "balcony": null,
    "balcony_notes": null,
    "garages": "0.0",
    "garages_notes": null,
    "carports": "2.0",
    "carports_notes": null,
    "flatlet": "0.0",
    "flatlet_notes": null,
    "domestic_accommodation": "0.0",
    "domestic_accommodation_notes": null,
    "flooring": null,
    "flooring_notes": null,
    "exterior": null,
    "exterior_notes": null,
    "roof": null,
    "roof_notes": null,
    "pool": false,
    "pool_notes": null,
    "garden_type": null,
    "garden_type_notes": null,
    "sea_views": false,
    "sea_views_notes": null,
    "security_notes": null,
    "store_room": false,
    "store_room_notes": null,
    "walling": null,
    "walling_notes": null,
    "pets_allowed": false,
    "pets_notes": null,
    "private_seller": false,
    "retirement_unit": false,
    "student_accommodation": false,
    "furnished": false,
    "open_hour_date": null,
    "open_hour_time": null,
    "open_hour_agent": null,
    "open_hour_agent_telephone_number": null,
    "bond_bank": null,
    "bond_bank_branch": null,
    "bond_bank_account_number": null,
    "bond_bank_balance": null,
    "managing_agent_email": null,
    "body_corp_email": null,
    "supervisor_email": null,
    "statistics": 560287,
    "quality": 536502,
    "project": null
}